swagger: '2.0'
info:
  version: '1.0'
  title: "PageTurner API"
  description: PageTurner is a simple API allowing clients to view information about books, their authors, and their reviews from PageTurner users.
  license:
    name: MIT
    url: https://github.com/switzersc/pageturner_api/blob/master/LICENSE
host: pageturner.apiblueprint.org
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /books:
    x-summary: Books Collection
    get:
      summary: List All Books
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Book'
          examples:
            application/json:
              - id: 98984500
                title: "Swamplandia!"
                description: "Thirteen-year-old Ava Bigtree has lived her entire life at Swamplandia!, her family’s island home and gator-wrestling theme park in the Florida Everglades. But when illness fells Ava’s mother, the park’s indomitable headliner, the family is plunged into chaos; her father withdraws, her sister falls in love with a spooky character known as the Dredgeman, and her brilliant big brother, Kiwi, defects to a rival park called The World of Darkness."
                publication_date: '2011-07-26'
                author:
                  first_name: Karen
                  last_name: Russell
                  website: https://www.penguinrandomhouse.com/authors/70463/karen-russell/
                  birthdate: UNKNOWN
                reviews:
                  - reviewer_name: Mallard Swift
                    reviewer_id: 00090
                    score: 90
                    summary: "I turned those pages!"
                  - reviewer: Pierre Valentine
                    reviewer_id: 00789
                    score: 89
                    summary: "Vivid, but I wanted more."
                  - reviewer: Opal Mild
                    reviewer_id: 00535
                    score: 77
                    summary: "Don't read if you're afraid of gators."
                  - reviewer: Rusty Rioja
                    reviewer_id: 13008
                    score: 100
                    summary: "PAGETURNER!"
  /book:
    x-summary: Individual Book
    get:
      summary: Show a Single Book
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            items:
              $ref: '#/definitions/Book'
          examples:
            application/json:
              id: 98984500
              title: "Swamplandia!"
              description: "Thirteen-year-old Ava Bigtree has lived her entire life at Swamplandia!, her family’s island home and gator-wrestling theme park in the Florida Everglades. But when illness fells Ava’s mother, the park’s indomitable headliner, the family is plunged into chaos; her father withdraws, her sister falls in love with a spooky character known as the Dredgeman, and her brilliant big brother, Kiwi, defects to a rival park called The World of Darkness."
              publication_date: '2011-07-26'
              author:
                first_name: Karen
                last_name: Russell
                website: https://www.penguinrandomhouse.com/authors/70463/karen-russell/
                birthdate: UNKNOWN
              reviews:
                - reviewer_name: Mallard Swift
                  reviewer_id: 00090
                  score: 90
                  summary: "I turned those pages!"
  /reviews:
    x-summary: Reviews Collection
    get:
      summary: List All Reviews
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Review'
          examples:
            application/json:
              - reviewer: Opal Mild
                reviewer_id: 00535
                score: 77
                summary: "Don't read if you're afraid of gators."
              - reviewer: Rusty Rioja
                reviewer_id: 13008
                score: 100
                summary: "PAGETURNER!"
    post:
      description: >-
        You may create your own review using this action. It takes a JSON
        object containing a review, and must reference the book it is associated with.
      summary: Create a New Review
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Review'
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/Review'
          examples:
            application/json:
                reviewer: Maria Ott
                reviewer_id: 13010
                score: 95
                summary: "Gripping!"
  /review:
    x-summary: Individual Review
    get:
      summary: Get a Single Review
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            items:
              $ref: '#/definitions/Review'
          examples:
            application/json:
              reviewer: Opal Mild
              reviewer_id: 00535
              score: 77
              summary: "Don't read if you're afraid of gators."
definitions:
  Book:
    title: Book
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      publication_date:
        type: string
      author:
        type: object
        properties:
          first_name:
            type: string
          last_name:
            type: string
          website:
            type: string
          birthdate:
            type: string
            format: date
      reviews:
        type: array
        items:
          $ref: '#/definitions/Review'
    required:
      - id
      - title
      - publication_date
      - author
  Review:
    title: Review
    type: object
    properties:
      id:
        type: integer
      reviewer_name:
        type: string
      reviewer_id:
        type: integer
        format: int32
      score:
        type: integer
        format: int32
      summary: 
        type: string
      full_text:
        type: string
    required:
      - id
      - reviewer_name
      - reviewer_id
      - score
      - summary
  Reviewer:
    title: Reviewer
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      reviews_count:
        type: integer
      reviews:
        type: array
        items:
          $ref: '#/definitions/Review'
    required:
      - id
      - name